package me.bowlmates.bowlmatesbackend.Controllers;

import me.bowlmates.bowlmatesbackend.Repositories.RestRepo;
import me.bowlmates.bowlmatesbackend.Repositories.UserRepo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.Map;

/**
 * REST API for admin functions
 */
@RestController // This means that this class is a Controller
@RequestMapping(path="/admin")
public class AdminController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepo userRepository;
    @Autowired
    private RestRepo restaurantRepository;

    /**
     * Current method is placeholder for future admin landing page
     * @return A map with a message verifying user has reached admin page
     */
    @GetMapping(value = "/", produces = "application/json")
    public Map<String, String> admin() {
        Map<String, String> response = new HashMap<>();
        response.put("message", "admin level");
        return response;
    }

    /**
     * Produces a test message for integration testing
     * @return A map with the test message
     */
    @GetMapping(value = "/test", produces = "application/json")
    public Map<String, String> test() {
        Map<String, String> response = new HashMap<>();
        response.put("message", "Test succeeded!");
        return response;
    }

}
