package me.bowlmates.bowlmatesbackend;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.ui.Model;

import org.springframework.validation.BindingResult;


@Controller // This means that this class is a Controller
//@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class TestController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepo userRepository;
    @Autowired
    private RestRepo restaurantRepository;

    @GetMapping("/register")
    public String showRegistrationForm(Model model){
        // create model object to store form data
        TestUser user = new TestUser();
        model.addAttribute("user", user);
        return "register";
    }

    @GetMapping("/restaurant")
    public String showRestaurantForm(Model model){
        // create model object to store form data
        TestRestaurant rest = new TestRestaurant();
        model.addAttribute("rest", rest);
        return "restaurant";
    }

    @PostMapping("/register/save")
    public String registration( @ModelAttribute("user") TestUser userDto,
                                BindingResult result,
                                Model model){
        TestUser existingUser = userRepository.findByEmail(userDto.getEmail());

        if(existingUser != null && existingUser.getEmail() != null && !existingUser.getEmail().isEmpty()){
            result.rejectValue("email", null,
                    "There is already an account registered with the same email");
        }

        if(result.hasErrors()){
            model.addAttribute("user", userDto);
            return "/register";
        }

        userRepository.save(userDto);
        return "redirect:/register?success";
    }

    @PostMapping("/restaurant/save")
    public String restaurant_info( @ModelAttribute("rest") TestRestaurant restData,
                                   BindingResult result,
                                   Model model){
        TestRestaurant existingTestRestaurant = restaurantRepository.findByAddress(restData.getAddress());

        if(existingTestRestaurant != null && existingTestRestaurant.getAddress() != null && !existingTestRestaurant.getAddress().isEmpty()){
            result.rejectValue("address", null,
                    "Your restaurant is already registered with BowlMates!");
        }

        if(result.hasErrors()){
            model.addAttribute("rest", restData);
            return "/restaurant";
        }

        restaurantRepository.save(restData);
        return "redirect:/restaurant?success";
    }

    @RequestMapping(path = "/test", produces="application/json")
    public String testApi() {
        return "This is an api test.";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<TestUser> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/")
    public @ResponseBody Iterable<TestUser> getAllUSers() {
        return userRepository.findAll();
    }

    SecurityContextLogoutHandler logoutHandler = new SecurityContextLogoutHandler();

}
